kind: pipeline
name: default

image_pull_secrets:
- DOCKER_CONFIG_JSON

steps:
- name: docker
  image: registry.build.lqm.io/dind
  privileged: true
  detach: true

- name: publish artifact
  image: registry.build.lqm.io/dind
  environment:
    DOCKER_HOST: docker:2375
    DOCKER_CONFIG_JSON:
      from_secret: DOCKER_CONFIG_JSON
    GSUTIL_CONFIG_JSON:
      from_secret: GSUTIL_CONFIG_JSON
  commands:
  - docker-login.sh
  - gsutil-login.sh
  - make publish-artifact
